version: 2.1

jobs:
  build-and-test:
    resource_class: 'arm.large'
    working_directory: /mnt/ramdisk
    docker:
      - image: node:20-bookworm-slim
    steps:
      - checkout
      - run:
          name: Install project deps
          command: npm i -g pnpm
      - run:
          name: Install deps
          command: pnpm install --reporter=append-only
      - run:
          name: Run tests & build
          command: pnpm run --reporter=append-only --recursive --if-present --aggregate-output "/^test$|^build$/"

workflows:
  build-and-test:
    jobs:
      - build-and-test
